In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Reading ratings file
# Ignore the timestamp column

# Reading movies file
df = pd.read_csv('movie_metadata.csv',usecols=['movie_title', 'genres'])

In [5]:
# Break up the big genre string into a string array
df['genres'] = df['genres'].str.split('|')
# Convert genres to string value
df['genres'] = df['genres'].fillna("").astype('str')
df

,genres,movie_title
0,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",Avatar
1,"['Action', 'Adventure', 'Fantasy']",Pirates of the Caribbean: At World's End
2,"['Action', 'Adventure', 'Thriller']",Spectre
3,"['Action', 'Thriller']",The Dark Knight Rises
4,['Documentary'],Star Wars: Episode VII - The Force AwakensÂ ...
5,"['Action', 'Adventure', 'Sci-Fi']",John Carter
6,"['Action', 'Adventure', 'Romance']",Spider-Man 3
7,"['Adventure', 'Animation', 'Comedy', 'Family',...",Tangled
8,"['Action', 'Adventure', 'Sci-Fi']",Avengers: Age of Ultron
9,"['Adventure', 'Family', 'Fantasy', 'Mystery']",Harry Potter and the Half-Blood Prince
10,"['Action', 'Adventure', 'Sci-Fi']",Batman v Superman: Dawn of Justice
11,"['Action', 'Adventure', 'Sci-Fi']",Superman Returns
12,"['Action', 'Adventure']",Quantum of Solace
13,"['Action', 'Adventure', 'Fantasy']",Pirates of the Caribbean: Dead Man's Chest
14,"['Action', 'Adventure', 'Western']",The Lone Ranger
15,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",Man of Steel
16,"['Action', 'Adventure', 'Family', 'Fantasy']",The Chronicles of Narnia: Prince Caspian
17,"['Action', 'Adventure', 'Sci-Fi']",The Avengers
18,"['Action', 'Adventure', 'Fantasy']",Pirates of the Caribbean: On Stranger Tides
19,"['Action', 'Adventure', 'Comedy', 'Family', 'F...",Men in Black 3
20,"['Adventure', 'Fantasy']",The Hobbit: The Battle of the Five Armies
21,"['Action', 'Adventure', 'Fantasy']",The Amazing Spider-Man
22,"['Action', 'Adventure', 'Drama', 'History']",Robin Hood
23,"['Adventure', 'Fantasy']",The Hobbit: The Desolation of Smaug
24,"['Adventure', 'Family', 'Fantasy']",The Golden Compass
25,"['Action', 'Adventure', 'Drama', 'Romance']",King Kong
26,"['Drama', 'Romance']",Titanic
27,"['Action', 'Adventure', 'Sci-Fi']",Captain America: Civil War
28,"['Action', 'Adventure', 'Sci-Fi', 'Thriller']",Battleship
29,"['Action', 'Adventure', 'Sci-Fi', 'Thriller']",Jurassic World
...,...,...
5013,"['Drama', 'Family']",Manito
5014,"['Action', 'Crime', 'Thriller']",Rampage
5015,"['Comedy', 'Drama']",Slacker
5016,"['Crime', 'Drama', 'Thriller']",Dutch Kills
5017,"['Comedy', 'Romance']",Dry Spell
5018,['Drama'],Flywheel
5019,"['Horror', 'Mystery', 'Thriller']",Exeter
5020,"['Drama', 'Horror', 'Thriller']",The Ridges
5021,"['Comedy', 'Drama', 'Romance']",The Puffy Chair
5022,['Drama'],Stories of Our Lives
5023,['Romance'],Breaking Upwards
5024,"['Sci-Fi', 'Thriller']",All Superheroes Must Die
5025,"['Comedy', 'Crime', 'Horror']",Pink Flamingos
5026,"['Drama', 'Music', 'Romance']",Clean
5027,['Drama'],The Circle
5028,['Horror'],Tin Can Man
5029,"['Crime', 'Horror', 'Mystery', 'Thriller']",The Cure
5030,['Drama'],On the Downlow
5031,"['Comedy', 'Horror', 'Thriller']",Sanctuary; Quite a Conundrum
5032,"['Crime', 'Drama']",Bang
5033,"['Drama', 'Sci-Fi', 'Thriller']",Primer
5034,['Thriller'],Cavite
5035,"['Action', 'Crime', 'Drama', 'Romance', 'Thril...",El Mariachi
5036,"['Crime', 'Drama']",The Mongol King
5037,"['Comedy', 'Drama']",Newlyweds
5038,"['Comedy', 'Drama']",Signed Sealed Delivered
5039,"['Crime', 'Drama', 'Mystery', 'Thriller']",The Following
5040,"['Drama', 'Horror', 'Thriller']",A Plague So Pleasant
5041,"['Comedy', 'Drama', 'Romance']",Shanghai Calling
5042,['Documentary'],My Date with Drew

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(analyzer='word',ngram_range=(1, 2),min_df=0, stop_words='english')
tfidf_matrix = tf.fit_transform(df['genres'])
tfidf_matrix.shape

(5043, 206)

In [7]:
from sklearn.metrics.pairwise import linear_kernel
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
cosine_sim[:4, :4]

array([[1.        , 0.71772763, 0.29121259, 0.0816324 ],
       [0.71772763, 1.        , 0.40574248, 0.11373729],
       [0.29121259, 0.40574248, 1.        , 0.20751026],
       [0.0816324 , 0.11373729, 0.20751026, 1.        ]])

In [12]:
# Build a 1-dimensional array with movie titles
titles = df['movie_title']
indices = pd.Series(df.index, index=df['movie_title'])

# Function that get movie recommendations based on the cosine similarity score of movie genres
def genre_recommendations(title):
    newtitle = title + '\xa0'
    idx = indices[newtitle]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:21]
    movie_indices = [i[0] for i in sim_scores]
    return titles.iloc[movie_indices]

In [13]:
genre_recommendations('Avatar').head(20)

15                                        Man of SteelÂ
39                            The Amazing Spider-Man 2Â
236       Star Wars: Episode III - Revenge of the SithÂ
237       Star Wars: Episode II - Attack of the ClonesÂ
240          Star Wars: Episode I - The Phantom MenaceÂ
520              The League of Extraordinary GentlemenÂ
1536        Star Wars: Episode VI - Return of the JediÂ
2051    Star Wars: Episode V - The Empire Strikes BackÂ
2687                               Highlander: EndgameÂ
3024                Star Wars: Episode IV - A New HopeÂ
3634         Beastmaster 2: Through the Portal of TimeÂ
4690                                           DestinyÂ
34                               X-Men: The Last StandÂ
47                          X-Men: Days of Future PastÂ
123                           X-Men Origins: WolverineÂ
210                                            X-Men 2Â
769                                      Reign of FireÂ
1145                             Underworld: EvolutionÂ
1432                    Underworld: Rise of the LycansÂ
1660                       Mortal Kombat: AnnihilationÂ
Name: movie_title, dtype: object